### ISSUE TITLE
Rename github repo

### ISSUE THREAD

**Issue by jchodera** [choderalab/openpathsampling#112]
Do you want to rename this GitHub repo from `opentis` to `openpathsampling`?

**Comment by jhprinz** [comment]
yes, if that is the final name we should change this. Is there a simple way to change the folder name also locally? Mine is still msm-tis

**Comment by jhprinz** [comment]
If I am correct we also need to rename the package itself to openpathsampling. I think I can do that using PyCharm very easily. This requires to rename everything that is somehow opentis to openpathsampling.

**Comment by jhprinz** [comment]
@jchodera 
There is still an error in uploading the conda package. Apparently the package name does not match (see line 1987 in the travis build #348 log https://travis-ci.org/choderalab/openpathsampling)
```
+binstar -t om-7a7d0d6e-e5c9-433a-8b30-4c0a0d72270b upload --force --u omnia -p openpathsampling-dev /home/travis/miniconda/conda-bld/linux-64/openpathsampling-dev-py27_0.tar.bz2
```
the error says 
```
[BinstarError] Package name on the command line does not match the package name in the file "/home/travis/miniconda/conda-bld/linux-64/openpathsampling-dev-py27_0.tar.bz2" 
```

I assume this has to do with the difference of `openpathsampling` vs `openpathsampling-dev`.

**Comment by jhprinz** [comment]
I think I found it. In meta.yml it named the package without the `-dev` lets see if this fixes it.

**Comment by jchodera** [comment]
Good catch!

**Comment by jchodera** [comment]
There it is!
https://binstar.org/omnia/openpathsampling-dev/files

I'm not sure if we've finalized the version naming convention for development packages (@kyleabeauchamp may know), but you may want to name the version `0.0.0`.

**Comment by jchodera** [comment]
We can also add this to the [omnia conda-recipes](https://github.com/omnia-md/conda-recipes).  You'll probably want to cut a release version before doing this though.

**Comment by kyleabeauchamp** [comment]
No comment

**Comment by jhprinz** [comment]
Named it Version 0.0.1 for now. The dev is fixed. 
I also needed to add a `conda convert` to create OS X and Windows versions. I have not seen this step in neither Yank nor mdtraj. Is there an easier way? Right now it seems to work and it uploads all conda packages and they install fine.

I am missing one pip package for visualization. How do you deal with this?

What about documentation, examples and scripts. These are usually not present in the conda package (although we could add scripts). Maybe we could have a little zipped folder that contains all of this, plus a complete "setup conda and install our stuff" script. Similar to what we already use in the travis build. We could also add an option to set up the complete conda environment if not present.

See #146 for discussion

**Comment by jchodera** [comment]
Huh.  I had no idea about `conda convert` until you mentioned this.  Was this really required for OS X packages?  We've never needed to use this before.  @kyleabeauchamp: Had you heard of this?

For the `pip` package: I would suggest adding a conda recipe to https://github.com/omnia-md/conda-recipes since `conda` doesn't play nicely with `pip`.  There is an easy way to make a `conda` recipe if the package exists in `PyPI` already:
http://conda.pydata.org/docs/build_tutorials/pkgs.html#using-conda-skeleton-to-build-from-a-pypi-package

Regarding documentation, examples, and scripts:
* Examples can be installed in the `~/anaconda/share/openpathsampling/examples/` directory. We currently do this [in the conda recipe for yank](https://github.com/choderalab/yank/blob/master/devtools/conda-recipe/build.sh#L7-L9), but will try to do this in `setup.py` instead because this will be more portable.
* For documentation, you can install the built documentation in `~/anaconda/docs/openpathsampling/`, just like OpenMM does.  Again, this can be done in the conda recipe, though it may be best if we can figure out how to do it in `setup.py` instead.
* For scripts, use the `entry_points` feature of `setup.py` to handle these, since they will then be installed correctly by conda as well:
https://github.com/choderalab/yank/blob/master/setup.py#L145

**Comment by dwhswenson** [comment]
Closing: further discussion on package dependencies can go into #154, but the headline for this issue is definitely solved.
