### ISSUE TITLE
Add support for bias in EnsembleHopMover

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#142]
Currently, `EnsembleHopMover` has plans to include a bias, but we aren't using it yet. My thought is that the bias should be called as:

```python
bias_value = self.bias(ens_from, ens_to)
```

We may implement a few convenience classes for the bias, but I don't think we should guarantee that the bias is restorable. Otherwise we need to make any user-defined function restorable.

In the example of fixed-bias SR-TIS, the matrix of bias values can be generated from a table of bias (approximate crossing probability) at each interface.

With this, I think we'll pretty much have everything implemented for fixed-bias SR-TIS. (Although we may need to do something clever for the SR-TIS version of the minus move.)

**Comment by jhprinz** [comment]
This will be part of #251.
