### ISSUE TITLE
add query for objects in storage

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#143]
should allow to filter objects, especially samples in the storage and be loaded/iterated:
- espcially only the ones in sample_sets
- allow to select different attributes with values / ranges, etc...
- might use lambda function to do so
- (optional) caching / creation of query objects that can be combined

Examples
```
storage.sampleset.samples( { 'replica' : 1})
```

**Comment by jhprinz** [comment]
I think I agreed to work on this...

**Comment by dwhswenson** [comment]
Should have been closed by #157.
