### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#153]
In a way, this is a continuation of #24, but we'll try to do it in a more methodical way. Feel free to edit this initial post to add more things to the task list. I'm treating this as a list of things I'm concerned might be confusing or might take a better name; some of them we might agree not to change.

I'll put discussion points for each of these in h4 (`####`) in comments below.

- [x] `PathMover` and `MovePath` confusion
- [x] `Momentum` doesn't contain momenta -- agreed that it doesn't matter at this point
- [x] [agreed] `Snapshot.atoms` and `Trajectory.atoms` vs. `Topology.n_atoms` #160
- [x] [agreed] `Trajectory.frames` vs `Trajectory.n_frames` (or `Trajectory.n_snapshots`) 
- [x] [agreed] `OrderParameter` vs. `CollectiveVariable`
- [x] [agreed] `LeaveX` `InX` `OutX` `HitX` rename to `PartOutX` `AllInX` `AllOutX` `PartOutX`
- [x] [agreed] `AndVolume`/`AndEnsemble`, `Or`, `Sub`, `Xor` rename to `Intersection`, `Union`, `RelativeComplement`, `SymmetricDifference`
- [x] [agreed] `Calculation` rename to `PathSimulator`

#### fix in PR #274 
- [x] [agreed] `LambdaVolume` to `CVRangeVolume`
- [x] [agreed] `ForwardAppended` to `Prefix`; `BackwardPrepended` to `Suffix`
- [x] [agreed] `root_mover` to `move_scheme`; and `default_movers` to `default_scheme`

**Comment by dwhswenson** [comment]
#### `PathMover` and `MovePath`

Obviously, these two names are too similar. I think we should leave `PathMover` the same and change `MovePath`, for the following reasons:

1. `MovePath` could be confused for `PathMover`, but not vice versa.
2. One might have a script with movers of things other than paths, so using just `Mover` is ambiguous.
3. "Path" is an overloaded term in this project. `MovePath` does not refer to trajectories, but to the path a move took.
4. `MovePath` is a record of the what happened in a move. So I think `MoveRecord` or `MoveLog` or something similar would be a clearer term to describe it. (I personally like `MoveRecord`, to avoid possible confusion with `logging`-related logs.)

#### `Snapshot.atoms` and `Trajectory.atoms` vs. `Topology.n_atoms`

We should be consistent in this. I think that `Object.atoms` can be reasonably interpreted as the list of atoms in `Object`. So I think that we should switch to `Object.n_atoms`. This also makes us consistent with MDTraj.

In general, where the `n` prefix is used to indicate "number of", I think we should be consistent in the usage `n_` instead of just `n`. (I actually prefer the latter, so it's probably my code that will have to change; but I think consistency is most important.)

#### `Trajectory.frames` vs `Trajectory.n_frames` (or `Trajectory.n_snapshots`)

See previous, but with the addition that perhaps we should use `n_snapshots` instead of `n_frames`. We regularly use the word frame in place of snapshot; that requires that the user always know that these are equivalent words. For local variables, that's probably fine, but the API should be clearer.

#### `Momentum` doesn't contain momenta

This still bothers me. But is it possible that before long we'll be able to remove the `Configuration` and `Momentum` objects? I already think they shouldn't be in the public API (interact with `Snapshot`s instead). The associated information (box vectors, energies) can be places in `OrderParameter`s.

Which brings us to:

#### `OrderParameter` vs. `CollectiveVariable`

We were planning to change this to `CollectiveVariable` (which is a more generically accurate term), right?

**Comment by jhprinz** [comment]
#### `PathMover` and `MovePath`
I agree and `MoveRecord` sounds good. Other possibilities we just brainstormed are `MoveHistory` or `MoveAncestory`. Maybe really just `MoveRecord` ?!
What about also changing PathMover? We are technically moving paths, but more generally in ReplicaSpace, but I have not better name...

#### `n_[]`
I agree to use `n_[something]` and also remove frame and use Snapshot. 

#### `Momentum`
Moving the energies to an order parameter -> agreed. For the storage of coordinates and velocities we still need an encapsulating object to keep track whether it has been saved or not, but we can indeed hide these objects from the user.

I personally like
```
Coordinates.xyz
Coordinates.box_vectors
Velocities.xyz
```
but I think John said that in his opinion `.xyz` is not clear enough. Third option would be to treat coordinates as a numpy array with additional .box_vectors options, but I subclassing numpy is tricky!

#### OP vs CV
Let'S pick one and use CollectiveVariable? I think we the system right now supports also Vectors so CV is better.

**Comment by dwhswenson** [comment]
(In the top post, I marked as "[agreed]" the ones where there's no more conversation to be had; we'll check them off as they get implemented.)

#### `PathMover` / `MovePath`

After I posted yesterday, I also thought of `MoveHistory`. I guess the questions are (1) Is there a risk of confusion somehow that `MoveRecord` would be misunderstood as something that was about to record (verb) the move, rather than being a record (noun) of a completed move? (2) Is there a risk that `MoveHistory` would be misinterpreted as the WHOLE move history; i.e., of all steps?

Those, to me, are the potential downsides of each of those names. Neither is very bad, so I don't think it really matters. I think misunderstanding (2) is more likely, so I have a slight preference for `Record`, but either works.

#### `Momentum`

I liked `.xyz` because it matched MDTraj's usage. However, I don't think there's an easy way to do the same for velocities. (And yes, as I recall, John was not fond of that.)

I think that `Velocity.velocities` is still pretty clear. But as long as `Configuration` and `Momentum` objects are hidden from the user, the naming isn't really important. This is the part of the program that even most contributors won't have to worry about.

**Comment by dwhswenson** [comment]
#### Renaming `LeaveX` etc:

Does the pairing `All` vs. `Part` and `In` vs. `Out` make sense for everyone?

**Comment by dwhswenson** [comment]
#### Renaming `And` etc (boolean terms) to `Intersection` etc (set terms)

As we've been working on the notation, @bolhuis pointed out that we've conflated the objects we define (ensembles and volumes) with their indicator functions. `Ensemble`s and `Volume`s are sets; when combining them to create another `Ensemble` or `Volume`, we should use the set theory terms. It's just convenient that the indicator function of, e.g., the intersection of two ensembles is the boolean `and` of the individual indicator functions.

We should keep the simple infixes of `&` and `|` (etc.), but rename the classes. I think the correct names (prepended to either `Volume` or `Ensemble`) are:

* `And` => `Intersection`
* `Or` => `Union`
* `Sub` => `RelativeComplement`
* `Xor` => `SymmetricDifference`

Also, we should probably disable `RelativeComplementEnsemble` and `SymmetricDifferenceEnsemble` for the time being. Their `can_append` functions won't work correctly until we can ensure that all ensembles have an explicit negated ensemble.

**Comment by jhprinz** [comment]
Agreed on all points. Intersection, etc is clearer. `All` is good and `Part` is probably the best option and balance between clearness and brevity. The other thing that came up would be `ForAll` `ExistsOne` the mimic the mathematical ∀ and ∃.

**Comment by dwhswenson** [comment]
Talking to @bolhuis today, he felt the `Calculation` name was unclear (sounds more like an Excel cell than a major simulation project). After some brainstorming, we thought that maybe `PathSimulator` would work best. Any other thoughts?

**Comment by jhprinz** [comment]
Yes, very good, this fit to the direction of the post I just made in #169. It could really be the thing that knows how to make MovePaths thus simulate new paths.

**Comment by dwhswenson** [comment]
#### `PathMover` and `MovePath`

@jhprinz : What did we decide on for this? We're keeping `PathMover`, and `MovePath` is become `PathMoveChanges` (or `PathMoveChange`, singular?). Something like that, right?

**Comment by jhprinz** [comment]
I named it `PathMoveChange` since it is just a single _Delta_ that can be stacked or nested like in a tree but it can always be seen a single change.

**Comment by dwhswenson** [comment]
#### `LambdaVolume`

As @jhprinz and I discussed a bit today, `LambdaVolume` feels a bit esoteric as a name. Perhaps something like `CVInRange` would be clearer? I think that most people will think of these more as restrictions on allowed values of CVs instead of volumes in phase space (equivalent ideas, but the question is which description is more familiar).

**Comment by dwhswenson** [comment]
#### `ForwardAppendedTrajectoryEnsemble` and `BackwardPrependedTrajectoryEnsemble`

I have mixed feeling about whether these objects are even necessary, but if we're going to have them, let's give them slightly less cumbersome names. I suggest `PrefixTrajectoryEnsemble` and `SuffixTrajectoryEnsemble`, respectively.

**Comment by jhprinz** [comment]
Should be fixed by PR #274 .

**Comment by dwhswenson** [comment]
Well, until we decide to rename something else. ;-)

**Comment by jhprinz** [comment]
Well... Yes, there was something with PathMovers, right :)

**Comment by dwhswenson** [comment]
Should have been closed by #275.
