### ISSUE TITLE
Update conda package dependencies

### ISSUE THREAD

**Issue by jchodera** [choderalab/openpathsampling#154]
* `matplotlib`?
* `ipython-notebook`?

**Comment by dwhswenson** [comment]
I think `svgwrite` might also be one that is still missing, although that has to come through `pip`. I believe there was some discussion on that in #112

**Comment by jchodera** [comment]
`pip` and `conda` don't get along very well, so it's best to create a new conda package for `svgwrite` and put it in https://github.com/omnia-md/conda-recipes.  This is easy to do if there is already a `pip` package using the `conda skeleton`:
http://www.peterbronez.com/Using%20PyPi%20Packages%20with%20Conda

**Comment by jhprinz** [comment]
- matplotlib 
- svgwrite
- ipython-notebook

are now all included. Closing
