### ISSUE TITLE
IPython 3.0.0 => notebook testing fails

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#164]
Apparently today IPython 3.0.0 was released and is installed automatically. I would propose to request IPython 2.4.x for now to keep the tests working. I can later try to figure out a way to fix the nbtesting. 

Apparently it is now easier to access the notebook and run the cells.

**Comment by dwhswenson** [comment]
Should this have been closed by #165? We should update any requirement list to IPython 3.0, though.

**Comment by jhprinz** [comment]
Yes, should have :) Closing now
