### ISSUE TITLE
Save link to associated mover for RandomChoiceMovePath

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#179]
Right now it looks like the `.mover` attribute for any `RandomChoiceMovePath` is always `None`. It would make some types of analysis much easier if that instead saved a pointer to the actual `RandomChoiceMover` that generated it. Would that be hard to implement, @jhprinz?

Example of where this is useful: assume for a given ensemble you randomly pick between two kinds of one-way shooting movers: one with uniform selection, one with a biased shooting point selection. You want to be able to tell which of these you're doing, but they are both shooting movers that operate on the same ensemble. It gets messy.

I found this because the way I was trying to get acceptance probabilities for all moves was going to be to loop over all samples and tally it for all the movers that are used (at all levels of the move tree). That only requires one sweep over the `movepath` data, which I thought would be optimal.

**Comment by jhprinz** [comment]
This sounds like a bug or missing implementation. If I am correct that should be almost trivial to do and I almost wonder why this is not already the case.

Just made a PR. Have a look and merge it or just add the line. It is that simple.

**Comment by jhprinz** [comment]
I think we can close this ?!

**Comment by dwhswenson** [comment]
Yep: I made a change to the PR statement that I hoped would autoclose it, but apparently it didn't.
