### ISSUE TITLE
Storage has linearly increasing time with number of trajectories

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#182]
See ipynb in gist https://gist.github.com/dwhswenson/0264e84fccc1414c313e for details. Note that the ipynb there uses the `TISTransition` class, so you'll need a branch with that in it (since that hasn't been merged to master yet).

**Comment by jhprinz** [comment]
This is no bug, just not the most efficient caching. I will add a PR to improve this.

**Comment by dwhswenson** [comment]
This has been fixed by #184, which was merged as a part of #201, and therefore can be closed, right?

**Comment by jhprinz** [comment]
Yes! Juhuu (german for Hooray!)
