### ISSUE TITLE
Make engines properly modular

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#185]
To make engines really modular, we shouldn't have any files where engine-specific code is mixed with either code from other engines or from the general framework. In particular, the files `tools.py` and `topology.py` should be cleaned up for this.

Making engines modular is important if we want other people to be able to add support for other engines. Mixing the code all over the place makes it hard to find what actually needs to be reimplemented to add more features.

**Comment by jhprinz** [comment]
Part of PR #197.

**Comment by dwhswenson** [comment]
Still need to separate Topology and Snapshots. Seeing `dynamiq_engine` as a basic approach.

**Comment by jhprinz** [comment]
Will be done in #434.

**Comment by dwhswenson** [comment]
I think that #434 finished everything I was asking for on this. There might still be some small bits of reorganization in the engines subpackage, but I consider this ready to close. If you agree, @jhprinz, feel free to close this!

**Comment by jhprinz** [comment]
Agreed! Yes, engines are now decoupled from the main OPS Code (although they require the Storable Object from netcdfplus.

Closing...
