### ISSUE TITLE
Separate `toy_dynamics_tis`

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#186]
In a real calculation, this would be split into (at least) 3 stages: (1) get initial transition trajectory; (2) equilibration; (3) production run.

I'm suggesting that we split this into at least two files: `toy_bootstrapping` and `toy_tis`. The first covers the first part, the second covers parts 2 and 3. A few advantages to this:

1. Saving the bootstrapping result instead of recalculating each time simplifies debugging in the notebooks -- indeed, that part of the calculation should be pretty much done.

2. Explaining bootstrapping is an unnecessary complication when introducing this to novices. You get the first transition trajectory by hook or by crook; bootstrapping is just one of many options. Splitting this lets us focus on the path sampling aspects.

I'm planning to make this split part of #183 (because I want this for development there), unless there are objections. My initial thought is that it would look like this:

#### `toy_bootstrapping.ipynb`

* Get first trajectory without saving it
* Use storage for the entirety of the bootstrapping procedure (`toy_bootstrap.nc`)
* Add in some of the move history visualization stuff (hoping @jhprinz can do that part later; I won't try to add it)

#### `toy_tis.ipynb`

* Load last trajectory of last ensemble from `toy_bootstrap.nc`, use that as initial condition for all ensembles (also mention how you could load the entire sample set, and how that might be better in this case, but use the single-trajectory approach because that's more general)
* Run the equilibration (shooting and path reversal only), saving to `toy_equil.nc`
* Run the production calculation (includes replica exchange), saving to `toy_tis.nc`

#### `toy_analysis.ipynb`

* Load everything from `toy_tis.nc` and do the analysis: path histograms, crossing probabilities, and replica flow within the interface set.

This will make testing and development a lot easier. Note that we'll still need more notebooks to describe how to do things at the network level: probably one for the simulation and one for the analysis. In practice, I think the recommended thing will be to start with networks (the 2-state version MSTIS network is probably best even if only doing a 2-state problem, at least if you want to get free energies, etc.)

**Comment by jhprinz** [comment]
I think this is a good separation, especially for testing and demonstation purposes. For this part I would also agree for keeping the storage separate in more than file and start in part 2 with trajectories from the bootstrapping file.

In general for storage I would really like to add a feature to store all the samples in one file which requires
some way to label SampleSets to the used Calculation.
Another way might be (but I need to check if that is really that easy) to use `groups` in netCDF format. You might consider this something like folders within the storage. So we can pretend to use separate files, but store everything in one file.

Considering my experience with the group in Vienna more tutorial notebook on various topics are a must and will boost the documentation a lot. We should have a tutorial on all major features, like
- Set-based objects (Volume / Ensemble)
- Ensemble construction / Sequential Ensemble
- Storage Saving / Querying
- Calculation / PathMoving
- Construction of PathMoves
- MovePath / MoveHistory evaluation
- Analysis
- Visualization
- etc...

**Comment by dwhswenson** [comment]
I think it will be much better for our users if we think about documentation first in terms of the level of the user (novice, beginner, power user, contributor) and second in terms of the subject.

What we explain to a novice about `PathMover`s is very different from what we'd tell a developer about the same. Statements like "the function `PathMover.move` takes a `SampleSet` as its argument and returns a `MovePath`" are completely unnecessary for most users; including that in documentation aimed at beginners will just confuse them. Of course, that statement is absolutely necessary for anyone who is going to write a new subclass of `PathMover`, and so it needs to be in the documentation somewhere.

It would also be much better to describe the documentation based on tasks the user is likely to want to accomplish, instead of thinking of it as a reference for each feature. Reference documents can be automatically generated from the code. However, understanding common tasks (e.g., "I want to create a state that's based on both a dihedral angle being in a given range and a specific hydrogen bond being formed") will not be easy to understand from the reference docs.

Overall, my point is this: our code is quite complex. It involves many different parts that interact in various ways. Understanding it from the bottom up is unreasonable to expect of anyone. So instead we should teach it from the top down. We should abstract what is needed at each level, and not cover anything more than that, giving documents that provide a successively more complicated tools. This will probably lead to longer documentation, but it will be easier for new users to understand.

My rough thought are that the docs would look like this (note: these are intentionally ordered)

1. Non-tutorial discussion of most important terms (volume, ensemble, path mover; perhaps also introducing sample/sampleset, probably not worrying about movepath yet)
2. Running a basic calculation with `Transition`s (includes the first setup of dynamics, uses a simple volume, default pathmovers; includes basic analysis and visualization (probably in a second notebook, but these would be done together)
3. Running a calculation with `TransitionNetwork`s (uses networks, a more complicated concept that single transitions, but easier to use in practice)
4. Creating more complicated `Volume` objects by various combinations
5. Adding other analysis techniques (looping over desired samples)
6. Adding other move-based analysis techniques (using the MovePath)
7. Creating more complicated moves using the toolkit we've created
8. Creating more complicated ensembles using the toolkit we've created
9. Details of storage, including how various decorators work
10. Coding new moves as subclasses
11. Adding support for new MD engines
12. Coding new calculation (PathSimulator) types
13. Coding new ensembles as subclasses

Appendix: Code reference (autogenerated)

The point is, until they reach number 6, there's no need to even talk in detail about MovePaths. Abstract it out. Similarly, as powerful as our approach to ensembles is, it's also pretty useless for most users. Teaching it early just leads to confusion, which is why I put it as number 8 (and the last thing before examples that actually require writing new code).

Details of this order are definitely flexible, but the main point is that the documentation should follow a path from "simplest way to get a calculation running" to "users can adjust the tiniest details of the calculation".
