### ISSUE TITLE
Handle already-open file (for interactive use)

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#187]
This isn’t terribly important, but is there any way to catch the case that a netCDF file has already been opened for writing?

The problem I occasionally hit is that, when working interactively in an ipynb, I try to open storage twice. One hack around this is to try to close the storage, catch and silently pass any NameError, and then open the storage. But that’s ugly and very distracting. Bad if we want the ipynb to also serve as user-facing documentation.

In my dream world, there’s a way to return the already-opened pointer. But maybe instead there’s a way to force close any other pointer to that file, and open a new one?

NetCDF raises a `RuntimeError: Permission denied`, so I assume you’d need another try-except inside the catching of that exception (for cases where it is really permission, and not a lock on an already-opened file).

**Comment by jchodera** [comment]
My only thought here is to introduce a level of software abstraction to manage these open netcdf file handles for you.  Can you do all your reading/writing (or at least opening) through a class that can cache a list of which files are open?

**Comment by dwhswenson** [comment]
@jhprinz and I talked about this over Skype on Friday. For now, what I'm doing is this:

```python
try:
    store_equil = paths.storage.Storage("toy_equil.nc", "w", template=template)
except RuntimeError:
    pass
```

It's a bit ugly, and not really correct (I believe netCDF raises the same runtime error whether I have already opened the file or whether I'm opening the file in a directory where I don't have write permission). But it lets me develop without having to worry about raising that error.

Considering it more, I think using that temporary fix while developing is probably best. This is just so I can make changes in the notebook and quickly rerun a bunch of cells without restarting the kernel or worrying about closing a file. The question is what the user means, in general, if asking to open a file twice for write access. I see two possibilities: (1) "I want to make sure I have this file open and keep writing to it from this object" (as in, just return the existing open object); (2) "I want to restart writing to this file" (as in, close anything already open, then open for writing).

I don't think that one of these is the more obvious intent than the other, so it's probably best just to require users to make their intent explicit in their scripts, and let netCDF raise its error when the intent isn't explicit.

I figure we'll just remove that temporary fix from the notebook once the whole notebook is written and seems to be working.

**Comment by jhprinz** [comment]
We might have an option to re-open a file and keep track of it (as John suggested) since that is what you mostly want for interactive sessions. It should be clear from the commands though. If a user runs a command which means open a new (empty) storage that is what should happen, even if the user thinks he wants to do something different.

**Comment by jchodera** [comment]
I'm not entirely sure why you would want the user to be able to specify the NetCDF read/write mode directly like this:
```
    store_equil = paths.storage.Storage("toy_equil.nc", "w", template=template)
```
The use cases are really only:
* I want to open a new storage file, failing if it already exists
* I want to open a new storage file, overwriting the existing one if it already exists
* I want to append to an existing storage file
* I want to read from a storage file for analysis purposes (but not writing or modifying it)

If you restrict the API to allow for only these cases, it should eliminate this problem.

**Comment by dwhswenson** [comment]
@jchodera : I like the premise of your suggestion, but it would still require some extra "all files handler" to deal with the problem. If I understand correctly, your suggestion boils down to using the "r" and "a" modes as they already exist, and splitting "w" into two cases: "w" as it already behaves, and "new", where "new" raises an error if the file exists.

But this does still require some handler to manage all files, because without it the following will error:

```python
storage1 = paths.storage.Storage("toy_equil.nc", "w", template=template)
storage2 = paths.storage.Storage("toy_equil.nc", "w", template=template)
```

Even if we assume that the user meant to do `storage1.close()` between those lines, the NetCDF error that comes out of that is "Permission denied". I don't know if there's an easy way to catch that error and distinguish between that case and the error you'd get from:

```python
storage = paths.storage.Storage("/etc/passwd", "w", template=template)
```

Even if you manage that (I guess by retesting permissions in the `except` block?) you'd still be unable to return the existing pointer.

But as I said in my comment above, I think the current work-around is good enough. As far as I'm concerned, this issue can be closed.

**Comment by dwhswenson** [comment]
Closing based on work-around being good enough.
