### ISSUE TITLE
Structure of Transition, TransitionNetwork and related objects

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#211]
This is to discuss the naming and tasks of the Transition objects.

When working to add an Alanine Example that samples the 6 states as in the [Du et al.] paper I was trying to reuse some of the existing TISTransition code and realized that I need some more clarification about what a `Transition` is.

I really love the way we can specify a TISTransition, it does everything and then take this object and analyze it. This is very powerful and easy at the same time. I found it somehow confusing though to use a TISTransition, because this kind of mingles the two concepts of a Transition (going from A to B) and the method we use to derive properties.

All I think we have to do is to rename TISTransition, etc.. to TISSampling and maybe just say:
- a `TransitionNetwork` consists of `Transitions` essentially a directed graph
- a (Directed) Transition is just a tuple of two Volumes/States, states are the nodes, transitions the edges
- `TISTransition` is renames to `TISSampling` and will be called e.g. like
    ```
    trans = tuple(stateA, stateB) # class is not necessary unless we have additional data
    tis = TISSampling(trans, stateA_interfaces) # defines the sampling strategy (and the analysis!)
    sampler = tis.sampler(storage=..., engine=...)
    # note sampler is not storable and can be changed anytime, it is not immutable!!!
    sampler.storage = ... # to change the storage used
    sampler.mover = ... # the complete logic in form of a PathMover
    sampler.sampleset = initial_sampleset
    sampler.run(100) # run it
    ```
- We could integrate Equilibration and Bootstrapping in the same way
    ```
    bs = TISBootstrapSampling(trans, stateA_interfaces) # defines the sampling strategy (and the analysis!)
    sampler = bs.sampler(storage=None, engine=...) # no storage
    sampler.sampleset = initial_sampleset
    sampler.run(100) # run it
    bootstrap_sset = sampler.sampleset
    ```

    ```
    eq = TISEquilibrationSampling(trans, stateA_interfaces).reuse(bs) # defines the sampling using the bootstrap setting
    sampler = eq.sampler(storage=None, engine=...) # no storage
    sampler.sampleset = initial_sampleset
    sampler.run(100) # run it
    bootstrap_sset = sampler.sampleset
    ```

- To get around the problem of reassigning the `Ensemble`s from one sampling to the next we could either:
    1. add a `.reuse(old_sampling)` that creates a new `Sampling` object that will use all existing ensembles from the underlying setting. It does this by cross checking all new and old ensembles and matching the already existing ones.
    2. when setting the simplest, we check which ensembles match to compensate that we redefined the ensembles (this might be dangerous since users are not aware of the problem)
    3. create a new sampleset that matches using a helper function `sset_new = sampler.match(sset_old)` (I think this is the current way to do it)
    4. keep a list of all created ensembles and make them unique if they already exist! (this could cause a severe slowdown since the shooters always construct new ensembles. And we would cache these. Or we try to only keep the saved ones, which is also problematic. Don't know, some think this is not the right wa to do it.)

- It would also be nice, if the `Sampler` would mark all generated SampleSets to be associates with a particular `Sampling` scheme `SampleSet.sampling = Sampling()`

- last the connection to MSMs/PMMs (projected Markov models): I will move this to another issue

**Comment by dwhswenson** [comment]
Back from Scotland, now I can write some thoughts on this:

First off,

**Comment by dwhswenson** [comment]
(first off, I need to not accidentally hit key combos that post the comment -- actual post coming in a little while)

**Comment by jhprinz** [comment]
+1

**Comment by dwhswenson** [comment]
Closing as resolved by oral discussion and implementation example.
