### ISSUE TITLE
CollectiveVariable equality is incorrect

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#228]
(Assigning this to @jhprinz because it needs to work with his fancy storage tricks for CVs.)

Easiest to explain with code:

```python
import openpathsampling as paths

def circle_sq(snapshot, center):
    return (snapshot.xyz[0][0]-center[0])**2 + (snapshot.xyz[0][1]-center[1])**2
    
opA = paths.CV_Function(name="opA", fcn=circle_sq, center=[-0.5, -0.5])
opB = paths.CV_Function(name="opB", fcn=circle_sq, center=[0.5, -0.5])

def xval(snapshot):
        return snapshot[0][0]

opX = paths.CV_Function(name="xval", fcn=xval)

print opA == opB
print opA == opX
```

Both of these should print `False`; instead they print `True`. I think this is because it is using the `dict` definition of equality (and the dictionaries are both empty, so far). It should use something based on the `fcn` and `kwargs` given -- or even the (required?) `name`.

This is needed for #227 (MSTIS networks), so I'm tagging this as "ASAP".

**Comment by jhprinz** [comment]
Should have been corrected by PR #230. Will close this for now.
