### ISSUE TITLE
Fast loading for `MovePathChange`s?

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#237]
The fast loading for `Sample`s introduced in #232 is nice; is it possible to do a similar thing with loading `MovePathChange`s?

`Sample`s and `MovePathChange`s are both used in analysis. It would be good to load both quickly.

**Comment by dwhswenson** [comment]
Also, add `SampleSet` to that.

**Comment by jhprinz** [comment]
SampleSet is no problem at all. MovePathChange is a little tricky, since the slow parts seems to be the JSON decoding. I will see, if I can find a faster way to deal with that.

**Comment by jhprinz** [comment]
Part of #251 and already working.
