### ISSUE TITLE
possible issue with shared_configuration

### ISSUE THREAD

**Issue by bolhuis** [choderalab/openpathsampling#238]
I don’t get why this test in shared_configuration gives the shared confs between self and other.

def shared_configurations(self, other):
       """
       Returns a set of shared snapshots

       Parameters
       ----------
       other : Trajectory()
           the second trajectory to use

       Returns
       -------
       set of Snapshot()
           the set of common snapshots
       """
       return set([snap.configuration for snap in self]) & set(list([snap.configuration for snap in self]))

Should the last line not contain other? Is this a possible bug?

**Comment by dwhswenson** [comment]
@jhprinz : you want to do the honors of fixing this? It should be a one-line fix, although it might be worth writing a test for it while we're fixing it.

I'll assign to you unless you send it back to me. ;-)

Also, is it necessary to wrap the comprehension in a `list()`? I thought it would be a list by construction.

**Comment by jhprinz** [comment]
No, the list is not necessary. I added some more tests to another PR that is not yet ready. So that will also come. This is a quick fix.

**Comment by dwhswenson** [comment]
Should have been fixed by #241.
