### ISSUE TITLE
Refactor : Renaming of functions and variables

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#24]
A new issue to discuss name changes:

#### Classes and member variables

class Snapshot()
[the object holding a configuration, a momentum and a reversed flag] 
=> keep
=> Frame()

Snapshot.configuration
[the pointer to the configuration] 
=> keep
=> Snapshot.coordinates
=> Snapshot.configuration
=> Snapshot.potential  (better not, although we could have potential.energy, kinetic.energy)

Snapshot.momentum
[the pointer to the velocities] 
=> Snapshot.velocity
=> Snapshot.velocities
=> Snapshot.kinetic

class Configuration() 
[the object holding coordinates, box_vectors, potential_energies per frame] 
=> keep
=> class Coordinates()

Configuration.coordinates 
[table of atom positions] 
=> keep
=> Configuration.xyz

class Momentum()
[the object holding velocities and kinetic energies per frame] 
=> class Velocity()
=> class Velocities()
=> class Kinetics()

Momentum.velocities
[the actual velocity table] 
=> Velocity.coordinates
=> Velocity.xyz
=> Velocity.velocity_xyz

#### Examples

coordinates_xyz = snapshot1.coordinates.xyz
velocities_xyz = snapshot1.velocities.xyz
snapshot1.coordinates.potential_energy
snapshot1.velocities.kinetic_energy
snapshot1.coordinates.box_vectors

#### Functions

Ensemble.forward(trajectory)
[the function that checks if a trajectory can still be in an ensemble if extended by one frame at the end ] => Ensemble.continue_foward(trajectory)

Ensemble.backward(trajectory)
[the function that checks if a trajectory can still be in an ensemble if extended by one frame at the beginning ] 
=> Ensemble.continue_backward(trajectory)

**Comment by jhprinz** [comment]
What about this. Is there anything we still need from this?

**Comment by dwhswenson** [comment]
I think we need to look over the code to find things that should be named more clearly. This issue partly addresses that, but it might make more sense to start over in a fresh issue to do the same (and use a task list in the first post of the issue to mark the items that are and aren't done; searching through a long thread is not optimal.)

**Comment by jhprinz** [comment]
Agreed again. Let's make a fresh start. This might also happen, when we work more on the documentation. There we should see any inconsistencies in the naming.

**Comment by dwhswenson** [comment]
Continued (more cleanly) in #153.
