### ISSUE TITLE
Add `canonical_move` function to PathMoveChange

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#243]
Following email with @bolhuis and discussions with @jhprinz, we should add something which identifies some sort of "canonical move" name for each move. The problem is that the only correct and unique name is the entire pathmovechange structure of subchanges. However, we think that, in general, something like the following (within `PathMoveChange`) should identify the relevant move:

```python
def canonical_move(self):
    pmc = self
    while len(pmc.subchanges) == 1:
        pmc = pmc.subchanges[0]
    return pmc.move
```

(That's pretty much what we said, right, Jan-Hendrik? Maybe the details of what it returns could be different: do we want to `PathMover`, the `PathMoveChange`, the class of the `PathMover`?)

**Comment by dwhswenson** [comment]
On more thought, maybe just return the change as the (get-only) property `pathmovechange.canonical`, which returns a `PathMoveChange`? This allows `pathmovechange.canonical.move` and so forth easily, and keeps the ability to access information about this specific move (which we lose when we return the `PathMover`).

**Comment by jhprinz** [comment]
I think the property is a good choice.

**Comment by jhprinz** [comment]
I will add this to my list of enhancement for PMC. I try to get this ready today.

**Comment by jhprinz** [comment]
Part of #251 and already implemented.
