### ISSUE TITLE
Visualization for PathMover decision tree

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#245]
It would be really nice to have a good automatic visualizer for the path move decision tree. I think that, based on the work @jhprinz is doing in #234, this might not be too hard to do. I was thinking something where

```python
paths.visualization.pathmovedecisiontree(root_mover, change=None)
```

might give you something like the attached image, and where

```python
paths.visualization.pathmovedecisiontree(root_mover, change=pathmovechange)
```

would highlight the actual branch followed by the given `pathmovechange`.

In the example I sketched, I visualized "leaf" nodes as circles, "Random choice" nodes as squares, and "Sequential" nodes by a hexagon. Arrows show the possible orders. In a real version, I think labels should come from hovering; the labels in this one are just to clarify what I mean in this example.

@jhprinz, how hard to you think this would be?

![pathmovedecisiontree](https://cloud.githubusercontent.com/assets/8178546/7474704/592d5d5e-f343-11e4-8e84-d961476446d4.png)

**Comment by jhprinz** [comment]
@dwhswenson 

This is not too difficult. It is some work, but pretty straight forward. Let me see, what I can come up with.
The thing that I have right now is vertical and can only display PathMoveChanges. Adding the complete mover should be quite easy and then highlighting a single move is also no problem.

To make it really look like a tree is little more work, but not too bad. I would add this is a second step.

**Comment by dwhswenson** [comment]
In the long term, visualizing like the picture above would be pretty cool (I remember you (@jhprinz) and I discussed that we had exact same picture in our heads for this, except that we chose different colors to highlight the path for a specific `pathmovechange` -- anything that shows that image to our users will help them understand how we think about these things.)

In the short term, I think it should be quite easy to let [NetworkX](networkx.github.io) do the layout for us (at least, all the nodes/edges should be something you can get from the changes in #234, if not directly from the `PathMover`s themselves). I think I'll be using NetworkX for visualizing RepEx networks at some point anyway, so I'm not shy about adding it as a requirement for OPS.

**Comment by jhprinz** [comment]
I was experimenting with networkX before and tried it today again, when I realised that (without additional packages) it cannot make a tree layout ?!?!?!? It seems that the main focus is for graph operations etc and not mainly visualization. But, it can export to various formats, so I chose to use D3 (which is Java and free and does not require any installation) and it creates SVG which runs even interactively in IPython Notebooks. Not sure how to best export it so PNG, but the result is pretty neat. 
![movetree](https://cloud.githubusercontent.com/assets/5091934/7496444/6f1e90de-f414-11e4-9810-328e936a6393.png)
I used a D3 circular tree plot and made it into half a circle. It was only a very quick hack, but it seems to work. It is also fully customizable and I do not need to write lots of python code to think about rendering.
I think I will play around with that and add a feature to show various PathMoveChanges within the whole tree. And submit a PR as soon as this is useable.

**Comment by dwhswenson** [comment]
Awesome -- that's pretty much what I expected/hoped for from NetworkX. I figured that to get an proper tree-like look would be hard (worth thinking about someday, but will take more work) but that something like what you show above wouldn't be too hard. Can you also highlight the path for a specific `pathmovechange`?

**Comment by dwhswenson** [comment]
(nevermind, I see you're working on the highlighting part -- got excited at the figure and stopped reading! :-P)

**Comment by jhprinz** [comment]
Yes, this is a little tricky, but should be doable. What might be more work is to have "vertical" lines for the Sequential moves, since they are on one level, but right now the lines are allo coming from the parent. Let's see. D3 is very powerful, but a little tricky to deal with. :)

**Comment by bolhuis** [comment]
Guys, this would be indeed great, but at this moment hardly a priority. I think it is much more important to be able to follow the flow of the simulation using the one line summaries. 
The most important about these summaries is that they also give the properties of the path. 

I really think that we should focus on providing the user with a summary of the simulation such as:
step = 1  :   move type = forward shot  ;   interface = 3: intlamb=0.15:  initial state A: final state A:  shooting point =10 ;trial length = 100 ; original path length = 50; new path len = 200 ;  lambda_max = 0.2   ensemble = true : metropolis = 0.9:  accepted 
step = 2  :   move type =- backward shot: interface = 4: intlamb=0.20:  initial state A: final state B:  shooting point =43 ;trial length = 33 ; original path length = 88; new path len = 133 ;  lambda_max = 1.5   ensemble = true : metropolis = 0.1:  rejected 
step = 3   : move type = revesal: interface 5: intlamb=0.25:  initial state A:  final state B:    new path len = 133 ;  lambda_max = 0.25   ensemble = true : metropolis = 1:  accepted 
step = 4  : move  type =  replica exchange : interface 2: intlamb=0.10:  initial state A:  final state A: lambda_max = 0.2   interface 3 :  intlamb=0.15:  initial state A:  final state A: lambda_max = 0.3 : exchange= allowed: accepted
etc etc

Are you looking into this?

Especially the type of the path is important.  E.g. a path can be typed as A1A A2A, A3A, AB, AC AD etc
Are there any tools to identify such path types?

Can we discuss this next week?

P

**Comment by dwhswenson** [comment]
Most of this is in a branch I've already done.

**Comment by dwhswenson** [comment]
Some of it requires rewrites of `ShootMover`.

**Comment by dwhswenson** [comment]
@jhprinz : would it be possible to get a PR with this, even if it is only partially working? (All I need is the ability to draw the figure you posted here.) It will be useful to quickly check that things are behaving as I expect as I build networks in #227.

**Comment by jhprinz** [comment]
I put up a PR for the current status and read a little more about D3 visualization. This has some pretty awesome features that would allow to watch the simulation and mover in real time :) But that is not a priority as @bolhuis said. I have almost finished the PMC changes and this should make it (again) easier to access what we want to know.

**Comment by jhprinz** [comment]
> Especially the type of the path is important. E.g. a path can be typed as A1A A2A, A3A, AB, AC AD etc
Are there any tools to identify such path types?

I think David did this at some (as he recently posted). There are a few natural ways to do this:
1. We write a function that turns `A1A` into an ensemble `ens` and we just test with `ens(trajectory)`
2. Since we usually already have `Ensembles` for these particular types we could have a function that
can output an `Ensemble` as a simplified string. It would be useful to add a `.state` and a `.interface`
attribute to a volume, which could be done by a wrapper volume:
```
stateA = TISVolume(
    name = 'stateA' 
    state = 'A',
    interface = 0,
    volume = LambdaVolume(...)
)
```

I would add this to the analysis package as an option to output a trajectory in terms of the simulation network/transitions.

**Comment by dwhswenson** [comment]
Solved a while ago... used in move schemes and strategies notebook.
