### ISSUE TITLE
Universal access to timestep as `engine.snapshot_dt` or `engine.snapshot_timestep`

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#255]
Some analysis routines (flux, in particular) need to know the timescale. That information is currently stored in the engine, but in an engine-dependent manner. I think we should make that accessible as `engine.snapshot_dt` or `engine.snapshot_timestep`, instead of `toy_engine.dt` vs `openmm_engine.options['timestep']`.

Also, this needs to be not the internal timestep, but the time per frame, so `dt*engine.nsteps_per_frame`.

The only catch is for dynamics that report frames at variable timesteps. I *think* path sampling can still make sense there, though the algorithms to calculate the flux would be different (you'd need actually total times instead of number of frames). But I don't think that's a scenario that needs a lot of worry at this point.

I would implement this as a get-only `@property` in each engine. It would be part of the required API for any new engine (since common analysis routines won't work without it).

Any opposition to this approach?

**Comment by jhprinz** [comment]
Good idea. So we force each engine to support this property. Do we want to use a unit for this to make conversion simpler or just a string like representation, e.g. 'fs' for femtoseconds. The storage / json pickling supports units, so this should not be difficult to store with an engine.
