### ISSUE TITLE
Clean up devtools scripts...

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#256]
Just as a reminder to go through the devtools stuff and look for redundant packages, etc...

**Comment by jhprinz** [comment]
I would close this for now. We have updated the devtools stuff so far. Objections? We could keep it open to remind us of a final cleanup, but we need to do that anyway. This was more to streamling the devtools in general.

**Comment by dwhswenson** [comment]
I'll close... the main devtools update we still need to make will be when we add support for python 3 (#70).

**Comment by jchodera** [comment]
Current recommended `devtools` scripts are here:
https://github.com/omnia-md/devtools
