### ISSUE TITLE
"Forget" caching

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#258]
Right now we cache everything, and the cache never forgets. Obviously, this won't work once we're dealing with hundreds of GB of data. (In fact, it's already getting into dangerous territory on my old laptop.)

I think the discussion of caching needs to split into two sides: sampling and analysis. Optimal solutions might be different for each of these.

One question to consider is how much we really need to cache positions and momenta. We want to keep the currently active trajectories while doing sampling, but we certainly don't need anything else. For analysis, I think we can do about the same: most analysis routines (especially any that will go to the samples) will loop over MC steps, and so will know the active samples for any step.

I'm a little concerned about scaling for this: it would be easy to fall into quadratic scaling. This should be linear. Looking up some of the algorithms used for garbage collection would be useful.

**Comment by jhprinz** [comment]
I will look into a smart way for better caching once #251 is done.

**Comment by jhprinz** [comment]
Should have been closed by #300 . Closing.
