### ISSUE TITLE
Normalization in replica exchange matrices

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#262]
We have a decent skeleton of the functions we want from #250, but I have a few questions to check details of how some things should be implemented. In particular, I'm hoping @jchodera and/or @bolhuis might be able to give some guidance on what the normalization should be for the matrices we create in the replica exchange analysis. 

Right now, we report two matrices: the mixing matrix and the transition matrix. Let me explain what I have implemented so far -- the sparsity structure of these is definitely what we want, but I'm not sure about what the relative values should be.

The way it is implemented now, what I'm calling the transitions matrix $T$ is such that 

$T_{ij} = P_{acc}( i<->j )$
$T_{ji} = 0$, 

where $P_{acc}( i<->j )$ is the acceptance probability of the replica exchange swap between $i$ and $j$, and $i>j$ (selecting a lower-triangular matrix).

What I'm calling the mixing matrix $M$ is then just $M = 0.5 (T + T^T)$ (where superscript T indicates transpose).

I see several options for normalization:

1. per trial of the exchange for this matrix element (which is what I'm doing now, but I don't think it is generalizable to all replica exchange schemes)
2. per MC step in the calculation (which gives much lower values, since many MC steps are not replica exchange moves -- matters if we includes self-transitions)
3. per MC step which includes a replica exchange (may be the hardest to implement)

One thing to keep in mind: some replica exchanges (e.g., minus move) are done less frequently than others, so the number of trials can be very different from cell to cell. 

Let's do a quick hypothetical to show the differences that we'd see with different normalizations. Assume only 2 swaps possible: minus-0 and 0-1. The minus move typically has ~100% acceptance. Say that the 0-1 swap has 25% acceptance, but is 4 times more likely to be called. Let's say we tried 200 total moves, with 50 shooting, 50 path reversal, 80 0-1 swaps, and 20 minus-0 swaps.

* In normalization 1, we would get `T[0,minus] = 1.0`; `T[1,0] = 0.25`
* In normalization 2, we would get `T[0,minus] = 0.1`; `T[1,0] = 0.1`
* In normalization 3, we would get `T[0,minus] = 0.2`; `T[1,0] = 0.2`

If we include self-transitions, this gets more complicated; in normalization 2, `T[0,0] = 0.8` (which is 8 times `T[1,0]`) whereas in normalization 3 `T[0,0]=0.6` (3 times `T[1,0]`).

Note that only first highlights the difference in acceptance ratios. But the whole point of modifying the frequency of selecting the move is to balance the number of *accepted* moves, so maybe the equality in number of accepted moves is what we want to see.

**Comment by jchodera** [comment]
It might be useful to take a look at our "replica exchange as Gibbs sampling" paper:
http://dx.doi.org/10.1063/1.3660669

There are a few takeaways from that work:
* More exchange attempts encourage better mixing of the overall Markov chain, and if it is cheap to do many exchange attempts, you should do this
* You want to look at the empirical transition probability T_{ij} = P(j, n+1 | i, n), the probability of observing a replica in state j at iteration n+1 given that it was in state i at iteration n.  
* For convenience, you can symmetrize this matrix when analyzing it, since the replica transition should obey detailed balance.
* The subdominant eigenvalue of the symmetrized transition matrix (the eigenvalue with the second largest magnitude) can be used to get a lower bound on the number of iterations required for the overall Markov chain to mix, where `tau = 1 / (1-lambda_2)` is the mixing timescale.

**Comment by jchodera** [comment]
I should also note that you can use `tau` to optimize the choice of states.  The smaller `tau` is, the faster the overall chain can mix.  Poor choices of states will lead to very large `tau`, or worse yet, the empirical transition matrix may be decomposable (have more than one unit eigenvalue).

**Comment by dwhswenson** [comment]
> You want to look at the empirical transition probability T_{ij} = P(j, n+1 | i, n), the probability of observing a replica in state j at iteration n+1 given that it was in state i at iteration n.

The question I'm not sure how to answer is, in the case of RETIS, how do we define "iteration n." As I understand it, many MD-based replica exchange approaches function in clearly defined cycles of running $t$ MD time followed by a replica exchange attempt (where "replica exchange attempt" means applying some permutation to the `(replica index, ensemble)` order).

Our approach just considers replica exchange as one of many legal Monte Carlo moves in the space of paths and path ensembles. We don't do $t$ shooting moves followed by replica exchange. We just randomly select whether to do shooting or replica exchange. Is "iteration n" based on all MC steps (meaning that shooting and path reversal are i->i transitions in replica space) or is it based on only the replica exchange attempts? Even the latter differs from the MD-like replica exchange in that the amount effort to relax within the ensemble varies from iteration to iteration.

It seems to me that the closest analogy to the MD-like approach is to normalize based replica exchange attempts (what I called normalization 3 above). Unfortunately, this is a bit of a pain -- it will require some sort of hack to say "this move is a replica exchange-type of move", because not all replica exchange moves are a `ReplicaExchangeMover` -- e.g., the minus move applies a permutation to the `(replica index, ensemble)` space, but it is not, itself, of class `ReplicaExchangeMover`. The current implementation uses a little multiple-inheritance hack to make it into one, but I think that specific approach is dangerous.

The minus move is just one example of the general case that user-created moves which involve at least one replica exchange should be seen as replica exchange movers by the analysis routines. A good solution requires something that will work in this general case.

Of course, if we use the all-MC-step normalization (number 2) instead of the only replica exchange move version, then we don't need to worry about this. That's why I was asking.

**Comment by dwhswenson** [comment]
Okay, I have a skeleton of a better implementation for finding whether a given move can lead to a replica changing ensembles now. Basically, we have a property `is_ensemble_change_mover` for all `PathMover`s. This defaults to False. Sample-generating `PathMover`s which involve changing ensembles (such as replica exchange, ensemble hop, etc.) need to set this to True in the class definition.

That's easy. Now we get to the fun part: movers with submovers. My argument is that any mover which *could* lead to an ensemble change should count as an ensemble change mover. So if any submover returns true, the main mover does as well. This is relatively easy to implement, and will work for any user-generated move scheme.

Finally, users can force a mover to lie. All the behavior described so far is the default, but you can either make an instance lie by setting its `self._is_ensemble_change_mover` variable, or you can make the whole class lie using `Class._is_ensemble_change_mover`. Perhaps you have a conditional sequential where you repex, do something, then repex back, but no matter what, the `(repID, ensemble)` pairs stay the same before and after the move. You can manually say "this isn't *really* a replica exchange" by using this trick.

All of this is illustrated in [a little ipynb I put into a gist](http://nbviewer.ipython.org/urls/gist.githubusercontent.com/dwhswenson/d9a1d69ff91550482ec4/raw/2c23c7c4ff3a1908e40f79ed110bb0c8952b9d1c/inherit_vs_flag.ipynb).

@jhprinz : Thoughts on this approach before I add in into the code?

---

Using this in the analysis: The current `analyze_exchanges` function works by looping over `pathmovechanges` (steps), and checking whether there's an instance of `ReplicaExchangeMover` in each move. This will be replaced by looping over `steps` and seeing whether `canonical.mover.is_ensemble_change_mover == True`.

**Comment by dwhswenson** [comment]
What I've implemented in #263 is the nearest version to the measurement that @jchodera suggested, however, I still find this a little problematic.

The matrix we measure now is the number of transitions from one ensemble to another, divided by the total number of ensemble-changing moves attempted ("ensemble-changing" includes replica exchange, ensemble hop, minus move, etc). The reason this remains problematic is that each replica exchange attempt is independent, so these numbers will inherently decrease as the number of ensembles increases. 

Compare two approaches:

1. You create one replica exchange "super-move", which consists of randomly selecting 3 replica exchanges to perform.
2. You make replica exchange 3 times more likely to happen. (This is basically how our move schemes work.)

Now, in the limit of a large number of replicas, I think these approaches should give very similar overall performance (i.e., the errors should converge at about the same rate as a function of wall time). For the sake of simplicity, let's say that the acceptance rate of all exchanges is the same in both cases (again, I think that's correct in the many-replica limit).

However, the values in the matrix for the first version will be 3 times higher than the second version, because the first version sees one move where the second sees three. This seems weird to me. The problem is in the way we count steps (i.e., as I originally phrased it, the normalization constant, or as it was in @jchodera's description, the iteration number).

In the example above, we can normalize to the number of replica exchanges included in the "super-move". But in more complicated schemes to generate the replica exchange permutation, we can't do that. Trying to include the minus move in this analysis complicates things further (I think there are assumptions here that replica exchange is computationally cheap, or at least constant in computational cost; the minus move is not cheap, and is much more expensive than regular replica exchange).

Anyway, what I've implemented works, but my concern is that if you're going to use it to compare two different methods, you need to be very certain that you're comparing apples to apples. Better mixing according to this matrix might not translate to better mixing based on wall time.

**Comment by jchodera** [comment]
I think there may have been some misunderstanding on what I meant by computing the empirical iteration-to-iteration transition matrix among states (here, ensembles).

In Yank, we clearly divide the overall simulation into "super moves" called iterations.  An iteration might consist of some Monte Carlo ligand displacement moves, followed by some dynamics, followed by many replica exchange attempts.  At the end of each iteration, we then record the new allocation of replicas to thermodynamic states.  We use this history to construct an "empirical count matrix" of transitions from one thermodynamic state to another, from which we can derive a normalized reversible transition matrix (from one of several ways that enforce reversibility).   The subdominant eigenvalue of this matrix allows us to examine whether we have mixing problems (if it is close to 1), and estimate how many iterations---at minimum---it would take to decorrelate replicas within the thermodynamic states.  This gives us an idea of how long we might want to run an individual simulation.  

Note that we may try many, many exchange attempts per iteration, but we only record the one transition observed from the end of the previous iteration to the end of this iteration.

If you want to compare two different methods where the wall clock time per iteration is very different, you *definitely* have to take this into account, but this empirical transition matrix in states is not what you would want to use to compare the true efficiency of different methods.   Instead, you would want to look at the replica correlation time of some more indicative property of decorrelation---such as the core-to-core (i,j) connection for the path being sampled.  The empirical thermodynamic state transition matrix is just to give an idea of whether you have problems with the spacing and overlap of your thermodynamic states (or, in your case, path ensembles).
