### ISSUE TITLE
Allow nameing for all objects

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#305]
I just thought it would be good to have naming for all objects. 
Usually these will only be a small number of special objects, like engines, movers, special snapshots, etc that we want to `tag`. For storage this means to have an additional list that has names and pointers to objects. WE could also allow tags for groups or ranges of objects. Like `initial_trajectories` -> `storage.trajectories[0:10]` and you could get these objects using `storage.load('initial_trajectories')`.

So in total the `netCDF+` has

```
storage.variables['name'] # all netCDF tables
storage.objects['name'] # all storable python objects
storage.tags['name'] # objects accessible by a tag
```

**Comment by dwhswenson** [comment]
Discussion in #372.
