### ISSUE TITLE
Help with binning for WHAM

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#310]
I ran a first Alanine beta -> alpha transition and wanted to analyze the transition. I get a problem with WHAM always reporting a `math domain` error and I presume this is cause by choosing a bad binning. What are the exact requirements for the binning so that I can adapt it?

**Comment by dwhswenson** [comment]
Please give more information. What are you passing as your histogram parameters? What is the traceback on the error?

The current WHAM is only set up for *increasing* order parameters, so that might be a problem. In fact, everything in the current process assumes that the order parameter to use for TIS increases. (You can make this true by using the negative of whatever other CV as your CV for TIS purposes.)

**Comment by dwhswenson** [comment]
@jhprinz : what's the status on this one? Did you find a solution? Can we close this issue?

**Comment by Asagodi** [comment]
During the last few simulations I also encountered this error. These are the histogram parameters:
mstis.hist_args['max_lambda'] = { 'bin_width' : 0.02, 'bin_range' : (0, 0.6) }
mstis.hist_args['pathlength'] = { 'bin_width' : 5, 'bin_range' : (0, 175) }
Would it help to change those?
https://gist.github.com/Asagodi/abf2b69f6ffe46255b7e#file-4c_10-ipynb

**Comment by dwhswenson** [comment]
I think this means that your interfaces don't have any overlap. That is, your WHAM sees at least one interface that has no contributions for some lambda where it should have contributions.

It is possible that inceasing the bin width avoid the problem; however, I think that's more likely to mask something more fundamental -- you may have your interfaces too widely spaced.

You can check this by directly checking the crossing probability for each interface -- when you plot them, there should be nothing that goes to zero within the overlap window.

I'm pretty sure that by the time the WHAM routine crashes here, you've already created all the interface crossing probabilities. Your notebook already has the code to access these. (Under "Path ensemble properties", subheading "Interface crossing probabilities").

If not, you can go through the process of creating them separately from the rate calculation:

```python
mstis.transtitions[(stateA, stateB)].all_statistics(storage, force=True)
```

With MSTIS, you'll have to do that once for each initial state (which final state you use won't matter). After that, you should be able to access the histograms.

**Comment by jhprinz** [comment]
If I understand correctly then if your spacing is so wide that none of the paths that are sampled from interface 1 do actually cross into interface 2 the estimated crossing probabiliy is zero. And we have no overlap to compute reweighting factors, or put differently the reweighting factors get zero/infinite which is a problem. You cannot reweight unrelated stuff.

Since our ensembles are nested, it would have been enough that you have e.g. a sample from interface 0 that goes to interface 2 because that infers that some samples from interface 1 will be part of interface 2 and it is solved.

So, if I understand all of this correctly, you cannot fix this by changing the bins in the analysis but you need to place your interfaces closer to get overlap. Is that correct? @dwhswenson

**Comment by dwhswenson** [comment]
That's how I understood it.
