### ISSUE TITLE
Replace `integrators.py` by using package `openmmtools`

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#327]
I have added openmmtools support in PR #162 and we might make this a requirement (since OpenMM is needed anyway this is a useful add-on) and we can use their VVVR implementation.

**Comment by jhprinz** [comment]
#162 will solve this by removing the need for the VVVR integrator.

**Comment by jhprinz** [comment]
Solved by #162 .

**Comment by dwhswenson** [comment]
Weren't we going to remove `integrators.py` before calling this closed (should be a real quick PR, right?)

**Comment by jhprinz** [comment]
I do this in the ABC PR. I was too lazy :)
