### ISSUE TITLE
Computation of CVs during production in `PathSampling`

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#328]
When merging the nb cleanup into the new storage it seemed like a useful feature to have a flag or option for pathsampling that will automatically compute and store a given set of cvs. This way analysis is faster and evaluation is fastest when snapshots are still in memory and not yet flushed.

**Comment by dwhswenson** [comment]
Agreed. I think it can be as simple as a list of CVs assigned to some variable in the `PathSampling` object (call it `saved_cv_list`?). Then every time the storage is sync'd, before the sync we make sure that all those CVs have a value associated with every snapshot that needs to be saved. The question is how to make this process fast.... but @jhprinz, I assume you have/can create tricks in `storage` to make it faster?

**Comment by jhprinz** [comment]
Already implemented in some PR is the past... Closing...
