### ISSUE TITLE
Strange Travis Error: Couldn't resolve host 'github.com'

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#333]
fatal: unable to access 'https://github.com/choderalab/openpathsampling.git/': Couldn't resolve host 'github.com'

Weird. Apparently it could not find github. Just restarted and it works... Anyone seen this error before?

**Comment by dwhswenson** [comment]
I think I may have seen that one before, although I don't think it ever repeated. The other day, for several hours the conda build on Travis was complaining that it didn't know where to find numpy.

Travis seems to be having a lot of errors like that recently. They get fixed pretty quickly, so I assume it's just issues with upgrades (the numpy issue) or with network connectivity on the virtual machines (when it can't find github). Anyway, I hope it's just a sign of temporary growing pains for Travis, and that the service itself won't be so undependable in the future.

Closing this issue, under the old saying: "Not my circus; not my monkeys." I don't think there's anything *we* can do to fix it.
