### ISSUE TITLE
Frequency for Livevisualisation

### ISSUE THREAD

**Issue by bolhuis** [choderalab/openpathsampling#339]
Hi, I don't know whether this should go here. The new live visualisation function in the mstis notebook looks great. However, there is not much changing at each time step while running. This is probably due to the many replia exchanges and the the rejections. I suggest plotting only with a certain frequency. is it possible to add a frequency variable? e.g something like mstis_calc.live_visualization.background = 100?  This will show only a new trajectory set every 100 moves. What do you think?

**Comment by dwhswenson** [comment]
You should be seeing something happen with every step. The live visualization shows trials in a thinner line (so even failed replica exchange trials show up as thinner lines on top of a thicker one). You might be running an old version; I seem to remember that I had a bug a while ago where the trials weren't getting shown.

But in any case, this is easy to add. I'll put together a PR on it tonight.
