### ISSUE TITLE
Travis fails...

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#354]
Anyone an idea why conda does not install on travis? All tests, including reruns of working old working ones fail after about 30seconds. Apparently the `conda` command is  not available.

**Comment by franknoe** [comment]
check if this is the channel problem. binstar.org has recently moved to 
anaconda.org

Am 04/11/15 um 00:12 schrieb Jan-Hendrik Prinz:
>
> Anyone an idea why conda does not install on travis? All tests, 
> including reruns of working old working ones fail after about 
> 30seconds. Apparently the |conda| command is not available.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/choderalab/openpathsampling/issues/354>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by jhprinz** [comment]
Hmmm, no, we had that error, too, but it was fixed already. Here is a copy of some of the output
```
installing: pycrypto-2.6.1-py27_0 ...
installing: _cache-0.0-py27_x0 ...
Python 2.7.10 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
devtools/ci/install.sh: line 25: conda: command not found
devtools/ci/install.sh: line 26: conda: command not found
devtools/ci/install.sh: line 27: conda: command not found
devtools/ci/install.sh: line 28: activate: No such file or directory
devtools/ci/install.sh: line 35: /home/travis/miniconda/envs/2.7/bin/pip: No such file or directory
```

line 25 is 
```
conda config --add channels http://conda.anaconda.org/omnia
```

is it possible that somehow the path to conda does not get added or updated?

**Comment by dwhswenson** [comment]
Probably not a channel problem, since it looks like the `Miniconda-latest` build claims that it works, and this is before we have even had a chance ask conda to install anything except itself.

First guess is to wait 15 minutes. I've had a few weird Travis issues get fixed after a few minutes.

Otherwise I'd say to try the obvious first checks: add `which conda`, `which python`, and `python -c "import sys; print sys.path"` around line 24 of the install script. Maybe `ls /home/travis/miniconda2` while you're at it.

**Comment by jhprinz** [comment]
found other people with that problem too, but you already had the answer...

It gets installed in `/miniconda2` not `/miniconda` which is the old path in all of our scripts...

**Comment by jhprinz** [comment]
just trying to see, if that fixes it.

**Comment by jhprinz** [comment]
Jup, works... I will add a quick PR...
