### ISSUE TITLE
TPS Network

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#360]
To do TPS with a similar workflow to the way we've set up TIS, we should have a TPS network. I'm inclined to have a the TPS network be a general multi-state approach, since the multi-state TPS reduces to 2-state TPS pretty easily.

Question, particularly for @bolhuis: which of the following do you think is the most useful way of setting it up?

Version 1: Useful if you're likely to only define a few specific pairs of states as transitions:
```python
tps = paths.TPSNetwork(transition_pairs=[(stateA, stateB), (stateB, stateA), (stateA, stateC), (stateC, stateA)])
```

Version 2: All states are allowed as both first and last state:
```python
tps = paths.TPSNetwork(states=[stateA, stateB, stateC[)
```

Version 3: Define the initial states, define the final states; all (non-self) transitions are allowed:
```python
tps = paths.TPSNetwork(initial_states=[stateA, stateB, stateC], final_states=[stateA, stateB, stateC])
```

I think my personal inclination is to make version 3 the standard way of setting it up (allowing, for example, sampling of all transitions out of stateA without including transitions out of B or C), with an extra method to allow version 1 (which allows you to select exactly which transitions are allowed). Version 2 is the simplest in the all-to-all case, but has no flexibility. It also doesn't make it possible to study only A->B (without also doing B->A).

Any strong preferences on this?

**Comment by bolhuis** [comment]
Hi, I think option 1 is too cumbersome. It grows  with N^2. As you say, version 2 is too restricted, and only  allows for an MSTIS multiple state interface. version 3 seems indeed an nice trade off between flexibility and compactness. 

So to be concrete:  A<->B which is probably the most used TPS set up would look like

tps = paths.TPSNetwork(initial_states=[stateA, stateB], final_states=[stateA, stateB])

this would allow both AB and BA paths, which is more efficient than just AB paths, certainly for twowayshooting. 

Another example
tps = paths.TPSNetwork(initial_states=[stateA, stateB], final_states=[stateC])

would sample AC and BC only.  This would be identical to 

tps = paths.TPSNetwork(initial_states=[stateAB], final_states=[stateC])

where stateAB= stateA or stateB. 

So, the question is: is the notation {StateA, stateB} not identical to the OR/Union of volumes that is already functional? Therefore the fps network could also be reduced to 

tps = paths.TPSNetwork(initialstate, finalstate)

and let the user decide  initialstate=stateA or stateB,   finalstate=stateA or stateB.
How about that? would this be flexibel enough?
