### ISSUE TITLE
ipynbtest fixes?

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#362]
Posting this mostly to prod @jhprinz, since I know he's already aware of the issue:

The `ipynbtest.py` script isn't catching all thrown errors. We think this has something to do with the ipython/jupyter "[Big Split™](http://blog.jupyter.org/2015/04/15/the-big-split/)" at IPython version 4.0; at least, that's when we started noticing the problem.

Some errors can propagate for a long time before `ipynbtest` registers them: I've seen errors in bootstrapping that only showed in the replica exchange networks -- after production runs and analysis! As a result, the errors that are raised aren't very informative, since they don't represent the actual point of failure. This makes debugging annoying.

This should get fixed ASAP. Also, I would personally like to see `ipynbtest` in its own repo. I plan to re-use it for other projects, and there's nothing specific to OPS in it. It will continue to grow and evolve, so giving it its own issue tracker is probably worth doing.

**Comment by jhprinz** [comment]
this will be fixed by #367 or better the updated ipynbtest. Turns was a stupid bug that did not test cells that had no output.

**Comment by dwhswenson** [comment]
Solved by #367 (or, at least, by updates in the new repo introduced by #367)
