### ISSUE TITLE
print states , ensembles and volumes

### ISSUE THREAD

**Issue by bolhuis** [choderalab/openpathsampling#364]
Hi, I think it would be useful to have a (number of ) functions that print out the set up of the network.
For instance 

print_state(stateA)
would result in:

state A is defined by 
  A= UnionVolume A1, A2
  A1 = CVRangeVolume  0 < opA1 < 0.5
  A2 = CVRangeVolume  0 < opA2 < 0.5

and print_interface_ensembles(stateA )
woud give something like

state A has 1 state definition  and  3 interface replica
interface 0:  CVRangeVolume  0 < opA < 0.5
interface 1:  CVRangeVolume  0 < opA < 0.6
interface 2:  CVRangeVolume  0 < opA < 0.6

print_network (MSTISnetwork) 
would be then the combined  result of 

print_state(stateA)
print_interface_ensembles(stateA )
print_state(stateB)
print_interface_ensembles(stateB )
print multiple_state_ensemble(MSTISnetwork)

I think functionality like this would give the user more grip on the network.
It might be that this is already implemented and i just can't  find it.

**Comment by dwhswenson** [comment]
This is already implemented by giving objects a string representation using the standard Python `.__str__()`. In practice, this means that you can access this information using Python's `print` function. Within the `mstis.ipynb` notebook, I get:

```
>>> print mstis

Multiple State TIS Network:
TISTransition: Out B
B -> B or all states except B
Interface: 0.0<opB<0.04
Interface: 0.0<opB<0.09
Interface: 0.0<opB<0.16
TISTransition: Out A
A -> A or all states except A
Interface: 0.0<opA<0.04
Interface: 0.0<opA<0.09
Interface: 0.0<opA<0.16
TISTransition: Out C
C -> C or all states except C
Interface: 0.0<opC<0.04
Interface: 0.0<opC<0.09
Interface: 0.0<opC<0.16

>>> print stateA

{x|opA(x) in [0.0, 0.04]}

>>> print mstis.from_state[stateA]

TISTransition: Out A
A -> A or all states except A
Interface: 0.0<opA<0.04
Interface: 0.0<opA<0.09
Interface: 0.0<opA<0.16

>>> # transition.stateB is the final state; 
>>> # in TIS includes everything except initial state
>>> print mstis.from_state[stateA].stateB 

({x|opB(x) in [0.0, 0.04]} or {x|opC(x) in [0.0, 0.04]})
```

The current way to print ensembles is a bit cumbersome, but gives a unique representation of the ensemble as a string:

```
>>> print mstis.from_state[stateA].ensembles[0] 

[
(
  x[t] in {x|opA(x) in [0.0, 0.04]} for all t
)
and
(
  len(x) = 1
),
(
  x[t] in (not ({x|opA(x) in [0.0, 0.04]} or ({x|opB(x) in [0.0, 0.04]} or {x|opC(x) in [0.0, 0.04]}))) for all t
)
and
(
  exists t such that x[t] in (not {x|opA(x) in [0.0, 0.04]})
),
(
  x[t] in ({x|opA(x) in [0.0, 0.04]} or ({x|opB(x) in [0.0, 0.04]} or {x|opC(x) in [0.0, 0.04]})) for all t
)
and
(
  len(x) = 1
)
]
```

Cleanup of this, and providing string representations of various levels of complexity from user-defined names to these detailed and unique strings, is the purpose of #233.

**Comment by bolhuis** [comment]
OK,  Thanks for clarifying! This helps a lot.
the result of 
print mstis

is now 

Multiple State TIS Network:
TISTransition: Out A
all states except B -> all states except B or B
Interface: 0.0<opA<0.04
Interface: 0.0<opA<0.09
Interface: 0.0<opA<0.16
TISTransition: Out B
B -> B or all states except B
Interface: 0.0<opB<0.04
Interface: 0.0<opB<0.09
Interface: 0.0<opB<0.16

clearly not correct. Any ideas?

**Comment by dwhswenson** [comment]
Closing here: @bolhuis's second comment was handled in #366 (and discussion in #361). I added a relevant point from the first comment in #233 (where further discussion of pretty-printing for volumes, ensembles, etc., should go).
