### ISSUE TITLE
Improved handling of named objects

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#372]
This is one of the two major points I think needs improvement in the storage (the other is about making stores storable -- different story): Better handling of named objects.

So far this works that we explicitely specify which objects (e.g. PathMovers, Engines, etc...) can have names and which ones don't (like Snapshots, Configurations, etc...). In general objects that contain running data like Samples, Snapshots, Trajectories do not have names while objects that create or operate on data (like engines, cvs, Movers, volumes, etc) do have names. For most object types only a small subset of objects will actually have a name while the others do not.

The setting of one object the allow for names will create an additional `[object]_name` variable in the netcdf file which will store names with the objects and most of the names will be empty or not used. It also requires handling and loading of all the names. Caching, etc...

I was wondering if it might be better to just add a special store to the storage which is called `.named`. It acts like a dictionary and references objects of _any_ type. While usual stores are more like a list `int -> object` this would be `str -> obj`. I would propose that names have to be exclusive, so one name can only point to one object or anything that can be pickled while the same object can have different names! Exactly like in a dict. 

When a file is opened the name dictionary will be cached so that access is fast.

#### Loading and saving of named objects

Usual load access would work like a dictionary
```
stateA = storage.named['stateA']
```
or using attributes
```
stateA = storage.named.stateA
```
and saving should work the same
```
storage.named['tis_AB'] = my_tis_ensemble
```
or we use a save function (different possibilities)
```
storage.named.save_as('tis_AB', my_tis_ensemble)
storage.save_as('tis_AB', my_tis_ensemble)
my_tis_ensembles.save_as(storage, 'tis_AB')
```

After saving there will be an entry in the store using two dictionaries
```
name_key : str
    contains the key of named object idx
name_json : str
    contains the json description of names object idx
```

#### Advantages

1 it's fast
2. requires minimal storage
3. You can store any object, like specific snapshots or even python dictionaries if you want, like meta information about a simulation. Anything that the ObjectJSON.simplifier can turn into JSON is acceptable.

#### Possible problems

The only problem I so far see with this approach is the detachment of name and object. If you load an object from a store and it has name then you do not know about it, unless you check the name cache
```
stateA = storage.volumes[0]
stateA.name  # ??? This will not work easily
```

We can of course check naming when an object is loaded, but that would trigger a search in the cache for every load operation which is not from cache. I think that is not optimal and should be avoided.
To deal with this we could

1. Objects do not have a name, but can only be stored under a name
2. We say only some object type scan the cache for names when loaded (this is probably closest to what we are doing now)
3. Only objects loaded by name will get their name property set. This could be confusing
4. Objects do not have a name property. But storage has a name function and a name makes only sense in connection with a storage.
    ```
    storage.name(my_obj)
    ```
5. Leave storage naming the way it is and just to the name storage in addition.

Right now I would prefer approach 4. Everyone could name objects the way they want and they can be found. You can ask for a name. If you do not save then the name of an object is somehow pointless since to know the name of your variable and complex object know how to get their content. The naming was only meant for loading from storage and that would be replaced.

One annoyance could be that each time you save an object to a new file (like after loading) you have to name it again, since names are storage bound.

#### Difference between names and descriptions

This is not too well thought out. But we should differentiate between a description and a (user given) name. I think _names_ should be given by the user and not automatically. So it a Network has several states that these do not have names given by the method, but the user can name the ingredients put into the creation of the network, like volumes, etc... and the network itself. He can also name objects created by the network and the user has access to. But this is really up to the user and he will not be able to name the object. 

I am not sure if what I mean should be the name, but rather a `reference` or `label` because it is external.
If so then we should not store the name, unless an object has a name property which we want to save and use loading by label only.

These are just thoughts to sort this out before I start an implementation.

**Comment by dwhswenson** [comment]
> Objects do not have a name, but can only be stored under a name
> Objects do not have a name property

I disagree entirely with this approach. The purpose of the name isn't to give it a unique place in storage. It is to make it meaningful for the user. Remember that `name` is used in the `print` process. That's the fundamental purpose of it.

Naming an object gives it semantic value. The whole point of a name is to give the object meaning that is clearer than a description. "State A" means a lot more than `{x | opA(x) in [0.0, 0.5]}`. When a user has complicated states combining various sets of required distances, it is a lot easier to name those with some string (probably of about a few characters) than for a human being to try to parse 3 lines of text describing the state.

I recommend against going down this road. This proposal will take away a lot of the features that makes OPS so friendly to use.

> I think names should be given by the user and not automatically.

See #369

**Comment by dwhswenson** [comment]
> I would propose that names have to be exclusive, so one name can only point to one object or anything that can be pickled while the same object can have different names! 

I think this is also the exact opposite of what we want. One object should only have one name. But more than one object can have the same name, especially because the user might use the same name in different contexts. A user might use "Interface 0" to refer to both the volume and the TIS ensemble associated with that volume.

**Comment by dwhswenson** [comment]
Just writing down some of what @jhprinz and I discussed on this topic during our Skype call today. I think we ended up with something that we both agreed worked for what we needed.

First, there are two different kinds of names. There's the `.name` attribute of an object, and then there's the name key used by storage. 

* Any object can have a name key. 
* Not all objects have a `.name`.
* If an object has a custom `.name`, that is also its name key.

Only custom names are used as name keys. Many objects have a default `.name` property which is overridden if `._name` is custom-set.

Important change: ***within any store, custom object names must be unique.*** This means that you can have a volume called `"lambda=0.1"` as well as an ensemble called `"lambda=0.1"`, but you can ***not*** have two volumes called `"stateA"`.

Within any store, the name can be used as a key for recovery. So:

```python
interface = storage.volumes['lambda=0.1']
ensemble = storage.ensembles['lambda=0.1']
template = storage.snapshots['template']
template = storage['template']
metadata = storage['metadata']
metadata_is_an_awful_name_for_an_ensemble = storage.ensembles['metadata']
```

All legal, all potentially return different things (although `storage['template']` could be the same as the snapshot template), and the namer of the last should be put in the stocks.

This allows the better loading from files that JHP wanted, and saved the naming conveniences and string representations that I wanted.

Did that describe everything, @jhprinz?

**Comment by jhprinz** [comment]
I think so... This will be part of my (hopefully) last storage update...

**Comment by jhprinz** [comment]
This should be closed. Only difference to the current implementation is that you cannot directly use `__getitem__` on `storage`. Not sure if that would break anything with netCDF so we use a store called `.tag`.

We could try and do so I you think it makes sense
```
storage['something']
```
vs
```
storage.tag['something']
```

**Comment by dwhswenson** [comment]
Closing. If we want to revisit the idea of `storage['something']` instead of `storage.tag['something']` it can be a separate issue/PR at a later date.
