### ISSUE TITLE
Attach a CV to snapshots as attribute

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#408]
Assume we have a CV called psi. Then we could add this as an attribute to all snapshots
```
cv_psi = CV_Function('psi', ..., register_as_attribute=True)
# get a snapshot
snap0 = storage.snapshots[0]
# regular way
print cv_psi(snap0)
# new way
print snap0.psi
```

This would make sense especially when we want to turn kinetic and potential energy into CVs.

Implementation is almost trivial using descriptors.

**Comment by dwhswenson** [comment]
In Skype discussion with @jhprinz : one of the problems with this, as fun as it looks, is that a Cythonized snapshot won't be able to dynamically add attributes.

**Comment by jhprinz** [comment]
Agreed. Let's close this for now.
