### ISSUE TITLE
Bug in tests using OpenMMTools

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#436]
(@jhprinz, you might already be fixing this one, but in case not, I'm making sure you're aware of it -- and assigning it to you, since you did the OpenMMTools support)

All of our PRs are failing tests in the `test_openmm_integration.ipynb` notebook, with error 

```
AttributeError ("'Residue' object has no attribute 'segment_id'")
```

in cell 4, which calls the `Topology.from_openmm` function, crashing on `topology.py` line 372.

I'm seeing this in both your recent updates to #429 and in my #435 (which doesn't touch OpenMM or topology stuff). I assume this is a change in upstream behavior, probably from OpenMMTools or MDTraj.

**Comment by jchodera** [comment]
I don't think we changed anything in openmmtools.

**Comment by dwhswenson** [comment]
The crash seems to be in mdtraj, but only when we load a topology via openmmtools. The change was in `mdtraj.Topology`, where the release notes for 1.6 (2 weeks ago) mention the `Residue.segment_id`.

I don't want to try to dive into this one too deeply myself, because @jhprinz knows the openmmtools interface much better than I do. Is it possible that the topologies from openmmtools testsystems don't include this `segment_id` attribute for the `residue`? JHP's example uses the `AlanineDipeptideVacuum` test system.

It looks like mdtraj has a test for its `Topology.from_openmm()` (which is the function that is crashing), but it only tests it by first using its `Topology.to_openmm()`. So it is also possible that there's a bug in mdtraj ...

And after looking through code to figure out what was going on, I finally saw this:

https://github.com/mdtraj/mdtraj/issues/1047

So this is on hold for a fix from MDTraj. If they don't fix it soon, we'll just downgrade to 1.5.1.

**Comment by jchodera** [comment]
We had this problem with Yank too. Just pin your requirements to 1.5.1 for now

**Comment by jchodera** [comment]
OpenMM doesn't have a segment_id property in Residue

**Comment by jhprinz** [comment]
Yes, this is either a change in the mdtraj or openmm `Topology` objects. The error comes when trying to convert an openmm topology object to mdtraj. The other direction works fine.

I added a quick fix for mdtraj but robert was not sure if `id` and `segment_id` are referring to the same information.

**Comment by jhprinz** [comment]
So far we need this to allow openmmtools to provide us with the Topology object. In all other cases we generated the openmm.Topology from the mdtraj one and this works fine.

We can either 

1. revert to `mdtraj` version 1.5.1 (which had the issue of changing the logger behaviour and outputting all deprecation warnings in ipython notebooks - this is fixed in 1.6.*)
2. exclude the openmmtools test for now since it does not really affect the rest of the framework.

Not sure what the best is. I assume this will be fixed soon.

**Comment by dwhswenson** [comment]
Yup, I agree those are the options. I honestly don't care which -- the openmmtools stuff is unlikely to be affected by any of *our* upcoming changes.

Which way do you think we're most likely to remember to come back to fix it?

Oh, actually -- maybe keep the test, but mark all cells as SKIP with ipynbtest? That way we'll see all those skips when looking at Travis logs and be more likely to remember to fix it later.

**Comment by jchodera** [comment]
Why not just pin mdtraj to a known working version? This is clearly a bug in that mdtraj release.

**Comment by jhprinz** [comment]
Maybe that is really the simplest solution. The only annoying point were all the pink warnings about deprecations popping up with that version.

**Comment by jhprinz** [comment]
Alright, changed it to 1.5.1 for now. Should we keep this open to remind us to revert this?

**Comment by dwhswenson** [comment]
> Should we keep this open to remind us to revert this?

Yes, I think that's the best way to make sure we don't forget and leave our required mdtraj pinned to an outdated version.

**Comment by jhprinz** [comment]
Okay, should not take too long for them to fix this anyhow.

**Comment by jchodera** [comment]
Note that the MDTraj bug has been fixed in https://github.com/mdtraj/mdtraj/pull/1089 but no new release has been cut yet.
