### ISSUE TITLE
Including MSM-TIS in Omnia?

### ISSUE THREAD

**Issue by jchodera** [choderalab/openpathsampling#44]
What would you guys think about eventually targeting `msm-tis` (or whatever you'd like to call this in the end) as part of the conda-installable `Omnia` collective?

http://omnia.md

The goal here is to collect a number of OpenMM-based packages into conda-packaged tools that share some common structures and file formats, with the main goal being ease of installation/use and interoperability.

We're trying to standardize some aspects of this, such as how documentation is made available, how travis tests are run, packaging standards, etc.

@kyleabeauchamp can provie more information about how this works with other projects like [mdtraj](http://mdtraj.org).

**Comment by jhprinz** [comment]
I think we already did this and it is up and running. Tested my first install in a conda environment.
So closing
