### ISSUE TITLE
Nightli.es?

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#462]
Did we intend in enable nightli.es support already? I think we should eventually, but not until after I fix the problem that we have some stochastic failures in the ipynb example tests, since initial trajectories don't always do what we want them to.

Since I know the nightlies include false failures, I was pretty much ignoring the fails (correctly -- it fixed itself in the most recent). Of course, the whole point is that the nightly should warn you of an upstream change that breaks your code. It's a little bit "boy who cried wolf," and I'd rather not be desensitized by the fake failures.

Is it okay to disable nightli.es support for the time being?

**Comment by jchodera** [comment]
Whoops, that was probably an errant click from my end.

Disabled now.
