### ISSUE TITLE
Problem in test_netcdfplus.ipynb

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#475]
I'm seeing regular test failures of `test_netcdfplus.ipynb` cell 73. Re-running often fixes. An example that failed (and I didn't re-run): https://travis-ci.org/choderalab/openpathsampling/builds/129109156, which is from a PR that is entirely documentation changes.

I suspect this is because that cell outputs a dictionary, and it expects the exact same string (meaning that the dictionary print order is uniquely defined, which isn't true). @jhprinz, could you fix this?

**Comment by dwhswenson** [comment]
Close by #477.

**Comment by dwhswenson** [comment]
Nope, that didn't seem to fix it. See https://travis-ci.org/choderalab/openpathsampling/builds/130191736.

**Comment by jhprinz** [comment]
Wierd. I am not able to reproduce the error... We look into that...

**Comment by dwhswenson** [comment]
Can ipynbtest output the mismatched text? That would go a long way toward debugging the problem.

**Comment by jhprinz** [comment]
Yes, trying right now...

**Comment by jhprinz** [comment]
I think this can be closed. `ipynbtest` was updated and should not report the error now.

**Comment by dwhswenson** [comment]
Agreed.
