### ISSUE TITLE
Box_Vectors not set in openmm engine

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#483]
I call this a serious but super easy to fix bug and did that already in the uuid PR #443.

When assigning the `current_snapshot` for openmm then the box_vectors are not set. I am actually not sure what openmm is simulating right now, but I assume that we do not using periodic boundaries. This is a serious bug, but easy to be fixed. That might be a reason that we get some NaNs in the Alanine simulations.

**Comment by dwhswenson** [comment]
Closed by #484.
