### ISSUE TITLE
storage creation not done in engines and make engines storable

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#79]
To allow to create several engine objects I would like to move the storage creation out of the engines and let this be handled by the user. So the storage has all the information about the system, n_atoms, topology, an initial configuration which is what an engine might need

```
storage = Storage('file.nc', mode='w/a', topology=..., n_atoms=..., configuration=...)
engine = OpenMM(storage=storage, opts) # creates new engine

# save the options in an engine used to generate it
storage.engines.save(engine)

# create an engine using the stored options and information in the store
old_engine = storage.engines.load(0, OpenMM) 
```

This would save exactly what we save right now, just in a more separate way.

Next, we would still have to pass the engine to the PathMover class. Either by setting the global using
```
PathMover.simulator = engine
```
or per mover
```
mover = ForwardMover(..., engine=engine)
```

Suggestions?

**Comment by jhprinz** [comment]
Is this done? I think I have implemented this already, but there is still the issue that PathMovers require an engine to be set globally. Maybe that is another issue and not present here. Will close this.

**Comment by dwhswenson** [comment]
Regarding the idea that PathMovers have a globally-set engine -- isn't the engine really only relevant for the shooting movers? (And movers that include shooting movers as sub moves). Maybe it makes sense to make it an argument in `__init__` for those.

**Comment by jhprinz** [comment]
Good point. A shooter should know the used engine. Let's just do that. I will make an issue.
