### ISSUE TITLE
Make use of test systems in openmmtools.testsystems?

### ISSUE THREAD

**Issue by jchodera** [choderalab/openpathsampling#88]
You should also feel free to make use of the test systems in [`openmmtools.testsystems`](https://github.com/choderalab/openmmtools/blob/master/OpenMMTools/testsystems.py) to set up some tests and examples for users.

We can also add examples you find useful to that file to make it easier to import and share them.

**Comment by jhprinz** [comment]
Will be implemented by #162.

**Comment by dwhswenson** [comment]
Fixed in #162
