### ISSUE TITLE
Reorganize examples?

### ISSUE THREAD

**Issue by jchodera** [choderalab/openpathsampling#89]
The `examples/` directory could use some reorganizing.  Right now, the contents are
```
alanine/
data/
ipython/
openmm/
```
Perhaps we could add `examples/README.md` as a master index of examples, and then have more meaningful subdirectory names that represent the nature of the system and dynamics under study?

**Comment by dwhswenson** [comment]
Discussing with @jhprinz, we've agreed on the following structure (eventually: before release, but not immediately):

```
examples/
   (everything that used to be in ipython/ subdir)
   data/
```

Anything worth saving in the `alanine` subdir will be turned into (nose)tests or ipython notebooks. Some from the `openmm` dir might become ipython notebooks, but most will be removed and original source pointed to from documentation.
